name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@c53ce905f3d89ff17317bf948fd329f9bef327a6
        with:
          linter: jetbrains/qodana-python
